testRandomProj <- function(d, targetDim, n) {
  eps <- sqrt(.Machine$double.eps)
  y <- matrix(rnorm(n*d), nrow=n)
  proj <- calculateProjection(y, targetDim)
  reembedded <- proj$embed(proj$project(y))
  rank <- sum(stats::prcomp(reembedded)$sdev > eps)
  rankIn <- sum(stats::prcomp(y)$sdev > eps)
  expect_equal(rank, min(targetDim, d, n))
  totalVar <- sum((y-rep(colMeans(y), each=nrow(y)))^2)
  remainingVar <- sum((y-reembedded)^2)
  reembedVar <- sum((reembedded-rep(colMeans(y), each=nrow(y)))^2)
  expect_equal(totalVar, remainingVar+reembedVar)
  expect_lt(remainingVar, totalVar*max(0,rankIn-targetDim)/rankIn + eps)
  expect_gt(reembedVar, totalVar*min(rankIn,targetDim)/rankIn - eps)
}

test_that("random", {
 testRandomProj(2, 2, 4)
 testRandomProj(3, 3, 4)
 testRandomProj(3, 2, 4)
 testRandomProj(4, 2, 4)
 testRandomProj(4, 3, 4)
 testRandomProj(2, 1, 4)
 testRandomProj(1, 1, 4)
 testRandomProj(2, 1, 2)
 testRandomProj(3, 1, 2)
 testRandomProj(3, 2, 20)
})
